pair/movie/urls.py
from django.urls import path
from . import views

# url namespace
# url을 이름으로 분류하는 기능

app_name = "movie"

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('create/', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

pair/pair/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
]

pair/movie/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class Review(models.Model):

    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now_add=True)

pair/movie/views.py
from django.shortcuts import render, redirect
from .models import Review


# Create your views here.
def index(request):
    review_ = Review.objects.all()
    context = {
        "review": review_,
    }
    return render(
        request, "movie/index.html", context
    )
    

def new(request):
    return render(request, 'movie/new.html')

def detail(request, pk):
    pk = Review.objects.get(pk = pk)

    context = {
        'pk': pk,
    }
    return render(request, 'movie/detail.html', context)

def edit(request, pk):
    pk = Review.objects.get(pk = pk)

    context = {
        'pk': pk,
    }
    return render(request, 'movie/edit.html', context)

def create(request):
    title = request.GET.get("title")
    content = request.GET.get("content")
    # 템플릿에서 데이터를 get
    
    # content필드는 default 값이 정해져있지 않으므로 content값을 넣는다.
    Review.objects.create(title=title, content=content)
    
    # context를 create한 후 return할 때 인자로 불러와도 되긴 하나 redirect로 해보자
    return redirect("movie:index")  # runserver하면 루트 주소로 뜬다.
    # 주소창에 naver를 navet로 입력해도 naver로 연결하는 역할

def update(request, pk):
  
    e = Review.objects.get(pk = pk)

    edited_title = request.GET.get("edited_title")
    edited_content = request.GET.get("edited_content")

    e.title = edited_title
    e.content = edited_content

  # 데이터를 수정한 것을 반영(save)
    e.save()

  # 데이터의 디테일 페이지로 리다이렉트
    return redirect('movie:detail', e.pk)

def delete(request, pk):
    Review.objects.get(pk = pk).delete()

    return redirect('movie:index')

pair/movie/templates/movie/detail.html
{% extends 'base.html' %} {% block content %}

<body>
  <h1>제목 : {{ pk.title }}</h1>
  <span> 내용 : {{ pk.content }} </span><br />
  <div style="text-align: center; margin-top: 1rem">
    <a href="{% url 'movie:edit' pk.pk %}" class="btn btn-success">리뷰 수정</a>
    <a href="{% url 'movie:delete' pk.pk %}" class="btn btn-warning"
      >리뷰 삭제</a
    >
  </div>
</body>

{% endblock %}

pair/movie/templates/movie/edit.html
{% extends 'base.html' %} {% block content %}

<form action="{% url 'movie:update' pk.pk %}">

  <span class="input-group-text" id="inputGroup-sizing-lg">제목</span>
  <div class="input-group input-group-lg mb-3">
    <input
      maxlength="80"
      type="text"
      class="form-control"
      aria-label="Sizing example input"
      aria-describedby="inputGroup-sizing-lg"
      name="edited_title"
      id=""
      value="{{ pk.title }}"
    />
  </div>

  <span class="input-group-text" id="inputGroup-sizing-lg">내용</span>
  <div class="input-group input-group-lg">
    <input
      type="text"
      class="form-control"
      aria-label="Sizing example input"
      aria-describedby="inputGroup-sizing-lg"
      name="edited_content" id="" value="{{ pk.content }}"
    />
  </div>

  <div style="text-align:right">
    <input style="margin-top:2rem;" class="btn btn-outline-danger" type="submit" value="리뷰 수정" />
  </div>
</form>

{% endblock %}

pair/movie/templates/movie/index.html
{% extends 'base.html' %} {% block content %}

<body>
  <div style="text-align: right">
    <a href="{% url 'movie:new'%}" class="btn btn-outline-danger"> 작성 버튼</a>
  </div>

  <table class="table">
    <tr>
      <th>리뷰번호</th>
      <th>리뷰 제목</th>
      <th>작성 시간</th>
    </tr>

    {% for r in review %}
    <tr>
      <td>{{ r.pk }}</td>
      <td>
        <a
          href="{% url 'movie:detail' r.pk %}"
          style="text-decoration: none; color: black"
        >
          {% if r.title == "" %}
          <!-- 제목이 ''면 -->
          제목 없음 {% else %} {{ r.title }} {% endif %}
        </a>
      </td>
      <td>{{ r.created_at.isoformat }}</td>
      <!-- isoformat : yyyy-mm-dd로 -->
    </tr>
    {% endfor %}
  </table>
</body>
{% endblock%}

pair/movie/templates/movie/new.html
{% extends 'base.html' %} {% block content %}

<form action="{% url 'movie:create' %}">
  <span class="input-group-text" id="inputGroup-sizing-lg">제목</span>
  <div class="input-group input-group-lg mb-3">
    <input
      maxlength="80"
      type="text"
      name="title"
      class="form-control"
      aria-label="Sizing example input"
      aria-describedby="inputGroup-sizing-lg"
    />
  </div>

  <span class="input-group-text" id="inputGroup-sizing-lg">내용</span>
  <div class="input-group input-group-lg">
    <input
      type="text"
      name="content"
      class="form-control"
      aria-label="Sizing example input"
      aria-describedby="inputGroup-sizing-lg"
    />
  </div>

  <div style="text-align:right">
    <input style="margin-top:2rem;" class="btn btn-outline-danger" type="submit" value="리뷰 쓰기" />
  </div>
</form>

{% endblock %}

pair/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, intial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"
    ></script>
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap"
      rel="stylesheet"
    />
    <style>
      body {
        font-family: "Black Han Sans", sans-serif;
      }
    </style>
  </head>

  <body>
    <div class="my-5">
      <h1 style="text-align: center">
        <span style="color: red">Cha & Moon </span
        ><span style="color: blue">Review</span>
      </h1>
    </div>
    <a href="{% url 'movie:index' %}">
      <button type="button" class="btn btn-outline-light">못찾겠지?HOME</button>
    </a>
    <header></header>
    {% block content %} {% endblock %}
  </body>
</html>